### ISSUE TITLE
Errors when cancel adding images.

### ISSUE THREAD

**Issue by JakubGolebiowski** [Raf-Mac475/Object_Detection#6]
When trying to load image and cancel process error occured:
```error
upload_button click
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\venv\test_t20_c117_p311\Lib\site-packages\PIL\Image.py", line 3135, in open
    fp.seek(0)
    ^^^^^^^
AttributeError: 'str' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\venv\test_t20_c117_p311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\projects\Object_Detection\Object_Detection.py", line 126, in upload_picture_btn_event
    self.my_image = customtkinter.CTkImage(light_image=Image.open(filename),
                                                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\venv\test_t20_c117_p311\Lib\site-packages\PIL\Image.py", line 3137, in open
    fp = io.BytesIO(fp.read())
                    ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
```
Could you add error exception? For example when process of reading image was canceled do not try to load image to tkinter level.
BR,
JG

**Comment by JakubGolebiowski** [comment]
Fixed with #8
